### ISSUE TITLE
petalinux2017.4 issue for ubuntu18.04

### ISSUE THREAD

**Issue by LeiWang1999** [z4yx/petalinux-docker#11]
I got this issue:

``` bash
environment: line 314: ((: 10#15~1 > 10#3: syntax error in expression (error token is "~1 > 10#3")
environment: line 318: ((: 10#15~1 < 10#3: syntax error in expression (error token is "~1 < 10#3")
```
And it seems unbuntu 18.04 which doesnt support it, look ahead [this thread](https://forums.xilinx.com/t5/Embedded-Linux/Ubuntu-18-error-when-running-settings-sh/td-p/864411) in xilinx formus.

**Comment by z4yx** [comment]
You may manually change the first line of Dockerfile to 16.04 for old Petalinux release.

Older version of Petalinux is no longer supported, so I updated the project description.
Sorry for inconvenience.

**Comment by LeiWang1999** [comment]
Thank you for your reply, i had replaced and it work for me now.
