### ISSUE TITLE
petalinux commands giving error 

### ISSUE THREAD

**Issue by bkumarrr** [z4yx/petalinux-docker#14]
HI All
I have installed petalinux and able to do configure a project ,then I have created a new project in different directory when I build this project using petalinux It is throwing some error like-
**user@3999--IOT--GGN:~/code/another_project/xilinx-zcu208-2021.1$ petalinux-build 
[INFO] Sourcing buildtools
[INFO] Building project
ERROR: /home/user/petalinux_sdk/components/yocto/source/ is missing in petalinux-tools.
ERROR: Installed Petalinux tools are broken. Please reinstall
ERROR: Failed to build project. Check the /home/user/code/another_project/xilinx-zcu208-2021.1/build/build.log file for more details...**
Note :When I follow the same steps for 1st project I am able to build 
Please help !

**Comment by z4yx** [comment]
I have created a project from Xilinx ZCU208 BSP, and built the project successfully.
```
vivado@cslab-7551x2:~/project/xilinx-zcu208-sdfec-2021.1$ petalinux-build 
[INFO] Sourcing buildtools
[INFO] Building project
[INFO] Sourcing build environment
[INFO] Generating workspace directory
INFO: bitbake petalinux-image-minimal
NOTE: Started PRServer with DBfile: /home/vivado/project/xilinx-zcu208-sdfec-2021.1/build/cache/prserv.sqlite3, IP: 127.0.0.1, PORT: 35755, PID: 6426
Loading cache: 100% |                                                                                                                       | ETA:  --:--:--
Loaded 0 entries from dependency cache.
Parsing recipes: 100% |######################################################################################################################| Time: 0:00:15
Parsing of 3471 .bb files complete (0 cached, 3471 parsed). 5106 targets, 215 skipped, 0 masked, 0 errors.
NOTE: Resolving any missing task queue dependencies
Initialising tasks: 100% |###################################################################################################################| Time: 0:00:06
Checking sstate mirror object availability: 100% |###########################################################################################| Time: 0:00:01
Sstate summary: Wanted 1351 Found 0 Missed 1351 Current 8 (0% match, 0% complete)
NOTE: Executing Tasks
NOTE: Tasks Summary: Attempted 4124 tasks of which 56 didn't need to be rerun and all succeeded.
INFO: Failed to copy built images to tftp dir: /tftpboot
[INFO] Successfully built project
vivado@cslab-7551x2:~/project/xilinx-zcu208-sdfec-2021.1$
```

**Comment by z4yx** [comment]
It seems like you didn't create and build your project in the Docker container. If that's the case, the problem came from Petalinux itself. You should then ask for help on the Xilinx support forum.
