### ISSUE TITLE
Simplify install with --skip_license option

### ISSUE THREAD

**Issue by tkutscha** [z4yx/petalinux-docker#16]
I noticed at the following link that you can skip the EULA screens with the undocumented option "--skip_license" listed at the following link: https://support.xilinx.com/s/question/0D52E00006iHq0ESAS/petalinux-run-install-script-autoaccept?language=en_US

Does this work for you?

Also, the README.md refers to launching petalinux 2018.1, when I think you meant 2020.02.  Did you really mean 2018.1?

**Comment by z4yx** [comment]
Current method works fine, so I don't want to switch to an undocumented method, which is subject to change.

I've corrected the version number in readme. Thanks for pointing out.
