### ISSUE TITLE
Issue installing petalinux

### ISSUE THREAD

**Issue by JohnTortugo** [z4yx/petalinux-docker#3]
Hey, did you by any chance got a problem similar to this one when installing petalinux?

```
INFO: Installing PetaLinux SDK to "/opt/Xilinx/petalinux/."
tar: ./tools/linux-i386/microblazeel-xilinx-linux-gnu/microblazeel-xilinx-linux-gnu/sys-root/usr/lib: Directory renamed before its status could be extracted
tar: ./tools/linux-i386/microblazeel-xilinx-linux-gnu/microblazeel-xilinx-linux-gnu/sys-root/usr: Directory renamed before its status could be extracted
tar: ./tools/linux-i386/microblazeel-xilinx-linux-gnu/microblazeel-xilinx-linux-gnu/sys-root: Directory renamed before its status could be extracted
tar: ./tools/linux-i386/microblazeel-xilinx-linux-gnu/microblazeel-xilinx-linux-gnu: Directory renamed before its status could be extracted
tar: ./tools/linux-i386/microblazeel-xilinx-linux-gnu: Directory renamed before its status could be extracted
tar: ./tools/linux-i386/aarch64-linux-gnu/aarch64-linux-gnu/libc/usr/lib/plugin: Directory renamed before its status could be extracted
tar: ./tools/linux-i386/aarch64-linux-gnu/aarch64-linux-gnu/libc/usr/lib: Directory renamed before its status could be extracted
tar: ./tools/linux-i386/aarch64-linux-gnu/aarch64-linux-gnu/libc/usr: Directory renamed before its status could be extracted
tar: ./tools/linux-i386/aarch64-linux-gnu/aarch64-linux-gnu/libc: Directory renamed before its status could be extracted
tar: ./tools/linux-i386/aarch64-linux-gnu/aarch64-linux-gnu: Directory renamed before its status could be extracted
tar: ./tools/linux-i386/aarch64-linux-gnu: Directory renamed before its status could be extracted
tar: ./tools/linux-i386/gcc-arm-linux-gnueabi/arm-linux-gnueabihf/libc/usr/lib: Directory renamed before its status could be extracted
tar: ./tools/linux-i386/gcc-arm-linux-gnueabi/arm-linux-gnueabihf/libc/usr: Directory renamed before its status could be extracted
tar: ./tools/linux-i386/gcc-arm-linux-gnueabi/arm-linux-gnueabihf/libc: Directory renamed before its status could be extracted
tar: ./tools/linux-i386/gcc-arm-linux-gnueabi/arm-linux-gnueabihf: Directory renamed before its status could be extracted
tar: ./tools/linux-i386/gcc-arm-linux-gnueabi: Directory renamed before its status could be extracted
tar: ./tools/linux-i386: Directory renamed before its status could be extracted
tar: Exiting with failure status due to previous errors
*********************************************
ERROR: Failed to install PetaLinux SDK into "/opt/Xilinx/petalinux/."
*********************************************
```

**Comment by z4yx** [comment]
I never got such problem before. Is it reproducible?

**Comment by Mon-ius** [comment]
INFO: Checking installation environment requirements...
INFO: Checking installer checksum...
INFO: Extracting PetaLinux installer...
INFO: Installing PetaLinux...
INFO: Checking PetaLinux installer integrity...
INFO: Installing PetaLinux SDK to "/home/monius/peta/."
.......................................................................................................................................................................................................................................................................tar: ./tools/linux-i386/microblazeel-xilinx-linux-gnu/microblazeel-xilinx-linux-gnu/sys-root/usr/lib: Directory renamed before its status could be extracted
tar: ./tools/linux-i386/microblazeel-xilinx-linux-gnu/microblazeel-xilinx-linux-gnu/sys-root/usr: Directory renamed before its status could be extracted
tar: ./tools/linux-i386/microblazeel-xilinx-linux-gnu/microblazeel-xilinx-linux-gnu/sys-root: Directory renamed before its status could be extracted
tar: ./tools/linux-i386/microblazeel-xilinx-linux-gnu/microblazeel-xilinx-linux-gnu: Directory renamed before its status could be extracted
tar: ./tools/linux-i386/microblazeel-xilinx-linux-gnu: Directory renamed before its status could be extracted
tar: ./tools/linux-i386/aarch64-linux-gnu/aarch64-linux-gnu/libc/usr/lib: Directory renamed before its status could be extracted
tar: ./tools/linux-i386/aarch64-linux-gnu/aarch64-linux-gnu/libc/usr: Directory renamed before its status could be extracted
tar: ./tools/linux-i386/aarch64-linux-gnu/aarch64-linux-gnu/libc: Directory renamed before its status could be extracted
tar: ./tools/linux-i386/aarch64-linux-gnu/aarch64-linux-gnu: Directory renamed before its status could be extracted
tar: ./tools/linux-i386/aarch64-linux-gnu: Directory renamed before its status could be extracted
tar: ./tools/linux-i386/gcc-arm-linux-gnueabi/arm-linux-gnueabihf/libc/usr/lib: Directory renamed before its status could be extracted
tar: ./tools/linux-i386/gcc-arm-linux-gnueabi/arm-linux-gnueabihf/libc/usr: Directory renamed before its status could be extracted
tar: ./tools/linux-i386/gcc-arm-linux-gnueabi/arm-linux-gnueabihf/libc: Directory renamed before its status could be extracted
tar: ./tools/linux-i386/gcc-arm-linux-gnueabi/arm-linux-gnueabihf: Directory renamed before its status could be extracted
tar: ./tools/linux-i386/gcc-arm-linux-gnueabi: Directory renamed before its status could be extracted
tar: ./tools/linux-i386: Directory renamed before its status could be extracted
tar: Exiting with failure status due to previous errors
*********************************************
ERROR: Failed to install PetaLinux SDK into "/home/monius/peta/."
*********************************************
Please refer to the PetaLinux Tools Installation Guide.

Check the troubleshooting guide at the end of that manual, and if you are
unable to resolve the issue please contact customer support with file:
   /home/monius/petalinux_installation_log

**Comment by Mon-ius** [comment]
I got it also. And I tried to https://github.com/coreos/bugs/issues/1095, https://blog.csdn.net/chxw098/article/details/79470508.

Still got this issues

**Comment by JohnTortugo** [comment]
I managed to workaround this by using bsdtar.

**Comment by Mon-ius** [comment]
I tried still failed

**Comment by Mon-ius** [comment]
Here are my config:

**Comment by Mon-ius** [comment]
Linux 3c95488ab50b 4.9.125-linuxkit #1 SMP Fri Sep 7 08:20:28 UTC 2018 x86_64 GNU/Linux

**Comment by JohnTortugo** [comment]
How did you do? In my case I created a shell script and made tar a alias to it. Then I was able to capture every call to tar and see which were the parameters. It was something ugly, but at the end worked. I can share it with you later.

**Comment by Mon-ius** [comment]
`apt-get install -y bsdtar && ln -sf $(which bsdtar) $(which tar)`

**Comment by Mon-ius** [comment]
# Guide : How-to-install-peta-linux-in-ubuntu18.04

Most effective guide for installing petaLinux in modern operating system.

## Reference

- Official Guide: `https://www.xilinx.com/support/documentation/sw_manuals/xilinx2018_2/ug1144-petalinux-tools-reference-guide.pdf`

- Issues forum: `https://forums.xilinx.com/t5/Embedded-Linux/Petalinux-install-permission-denied-petalinux-env-check-in-tmp/td-p/838988`


## Configuration

HardWare

- OSX Mojave(host)
- Ubuntu 18.04(vm in parallel)/Debian 9.X(vm in parallel) or CentOS 7.0+(vm in parallel)
- 100 GB Space

SoftWare

- Vivado HLS
- PetaLinux SDK
- Version: v2018.3
- Download Address: `https://www.xilinx.com/member/forms/download/xef.html?filename=petalinux-v2018.3-final-installer.run` 
- Location: `/opt` 
---
- Bash
- Version: v4.3
- Download Address: `http://archive.ubuntu.com/ubuntu/pool/main/b/bash/bash_4.3-14ubuntu1_amd64.deb`

## Requirements
It's different from the solution in reference.(python, iproute2, xinetd, tftpd-hpa,libtool-bin)
### Ubuntu (apt)
Noted: failed to install.
> `sudo apt-get install libtool-bin python python3 tofrodos iproute2 gawk xvfb gcc git make net-tools libncurses5-dev tftpd zlib1g-dev  libssl-dev flex bison libselinux1 gnupg wget diffstat chrpath socat xterm autoconf libtool tar unzip texinfo zlib1g-dev gcc-multilib build-essential libsdl1.2-dev libglib2.0-dev screen pax gzip xinetd` <br>

Other version
- sudo dpkg --add-architecture i386
- sudo apt-get update
- sudo apt-get install tftpd-hpa zlib1g:i386

### Debian (apt)

#### VM or Bare install
Noted: Success!
> `sudo apt-get install libtool-bin python python3 tofrodos iproute2 gawk xvfb gcc git make net-tools libncurses5-dev tftpd zlib1g-dev  libssl-dev flex bison libselinux1 gnupg wget diffstat chrpath socat xterm autoconf libtool tar unzip texinfo zlib1g-dev gcc-multilib build-essential libsdl1.2-dev libglib2.0-dev screen pax gzip xinetd tftpd-hpa tftp-hpa` 

Enable tftp service
- sudo systemctl enable tftpd-hpa
- sudo systemctl restart tftpd-hpa

#### Docker image
Noted: failed to install.
- sudo apt-get install -y bsdtar && ln -sf $(which bsdtar) $(which tar)
- sudo apt-get install less
- export tar='bsdtar'
> `sudo apt-get install libtool-bin python python3 tofrodos iproute2 gawk xvfb gcc git make net-tools libncurses5-dev tftpd zlib1g-dev  libssl-dev flex bison libselinux1 gnupg wget diffstat chrpath socat xterm autoconf libtool tar unzip texinfo zlib1g-dev gcc-multilib build-essential libsdl1.2-dev libglib2.0-dev screen pax gzip xinetd`  <br>

- `sudo apt install tftpd-hpa tftp-hpa lib32ncurses5 lib32z1`

Enable tftp service
- sudo systemctl enable tftpd-hpa
- sudo systemctl restart tftpd-hpa

### CentOS (yum)
Noted: failed to install.
> `yum install dos2unix gawk  gcc  gcc-c++  xvfb  git  make  netstat  ncurses-devel  tftp server  zlib-devel openssl-devel  flex  bison  libselinux  gnupg  wget  diffstat  chrpath  socat  xterm  autoconf  libtool  tar  unzip  texinfo  zlib1g-dev  gcc-multilib  build-essential  libsdl1.2-dev  libglib2.0-dev  SDL-devel  glibc-devel  32-bit glibc  glib2-devel  automake  screen  pax  gzip  libstdc++ bzip2 patch net-tools texinfo xorg-x11-server-Xvfb` 

## Steps
- PetaLinux requires no root install!!!
- PetaLinux requires bash version 4.3 !!!
- PetaLinux install file is so f*****g stupid that it cannot identify the `.`, so you need to give an absolute path.
- I have to create an empty directory in `/opt/peta` for installation. `mkdir -p /opt/peta`

### 0. Solve sh problem.(replace 'ash' with 'bash' 4.3 version)

- apt install sudo (docker)
- `wget http://archive.ubuntu.com/ubuntu/pool/main/b/bash/bash_4.3-14ubuntu1_amd64.deb`
- `sudo apt install ./bash_4.3-14ubuntu1_amd64.deb`
- `sudo rm /bin/sh`
- `sudo ln -s /bin/bash /bin/sh`

### 1. Create an new user 'monius' and give sudo privilege.

- `sudo adduser monius`
- `sudo usermod -G sudo monius` (ubuntu, debian)
OR
- `sudo usermod -aG wheel monius` (centos)

### 2. Occupy the `/opt` directory with monius.(Sweet~XD)

- `sudo chown -R monius:monius /opt`

### 3. Create an empty directory for stupid XILINX.(Now you're monius)

- `cd /opt`
- `mkdir -p /opt/peta`

### 4. Install PetaLinux in your VM ubuntu os.

- `cd /opt`
- `sudo chmod +x ./petalinux-v2018.3-final-installer.run`
- `./petalinux-v2018.3-final-installer.run  /opt/peta`

### 5. Activate environment.

- `cd /opt/peta`
- `source ./settings.sh`

### add auto scripts to .bashrc file.(additional step)

- echo "source /opt/peta/settings.sh > /dev/null 2>&1" >> ~/.bashrc
- source ~/.bashrc

## Author

- Monius
- `https://github.com/Mon-ius`

**Comment by Mon-ius** [comment]
Here are my steps. Bad manual

**Comment by Mon-ius** [comment]
Still failed in my debian docker image.
```

INFO: Checking installation environment requirements...
WARNING: This is not a supported OS
INFO: Checking free disk space
INFO: Checking installed tools
INFO: Checking installed development libraries
INFO: Checking network and other services
WARNING: No tftp server found - please refer to "PetaLinux SDK Installation Guide" for its impact and solution
INFO: Checking installer checksum...
INFO: Extracting PetaLinux installer...

LICENSE AGREEMENTS

PetaLinux SDK contains software from a number of sources.  Please review
the following licenses and indicate your acceptance of each to continue.

You do not have to accept the licenses, however if you do not then you may
not use PetaLinux SDK.

Use PgUp/PgDn to navigate the license viewer, and press 'q' to close

Press Enter to display the license agreements
./petalinux-v2018.3-final-installer.run: line 124: less: command not found
Do you accept Xilinx End User License Agreement? [y/N] > y
./petalinux-v2018.3-final-installer.run: line 124: less: command not found
Do you accept Webtalk Terms and Conditions? [y/N] > y
./petalinux-v2018.3-final-installer.run: line 124: less: command not found
Do you accept Third Party End User License Agreement? [y/N] > y
INFO: Installing PetaLinux...
tar: Error opening archive: Failed to open '/dev/st0'
INFO: Checking PetaLinux installer integrity...
INFO: Installing PetaLinux SDK to "/home/monius/peta/"
*********************************************
ERROR: Failed to install PetaLinux SDK into "/home/monius/peta/"
*********************************************

Please refer to the PetaLinux Tools Installation Guide.

Check the troubleshooting guide at the end of that manual, and if you are
unable to resolve the issue please contact customer support with file:
   /home/monius/petalinux_installation_log
```
```

monius@3c95488ab50b:~$ cat /home/monius/petalinux_installation_log

INFO: Checking installation environment requirements...
INFO: Checking installer checksum...
INFO: Extracting PetaLinux installer...
INFO: Installing PetaLinux...
INFO: Checking PetaLinux installer integrity...
INFO: Installing PetaLinux SDK to "/home/monius/peta/"
tar: Option --checkpoint=.5000 is not supported
Usage:
  List:    tar -tf <archive-filename>
  Extract: tar -xf <archive-filename>
  Create:  tar -cf <archive-filename> [filenames...]
  Help:    tar --help
*********************************************
ERROR: Failed to install PetaLinux SDK into "/home/monius/peta/"
*********************************************
Please refer to the PetaLinux Tools Installation Guide.

Check the troubleshooting guide at the end of that manual, and if you are
unable to resolve the issue please contact customer support with file:
   /home/monius/petalinux_installation_log
```

**Comment by Mon-ius** [comment]
Could u plz send yours to me, thanks.

**Comment by JohnTortugo** [comment]
I ended up collecting all calls to tar (using try and error) and mapping them to bsdtar. This is the script I use as an alias to `tar`

```
#/bin/bash

if [ ! -e /tmp/first.txt ]; then
    # --exclude=*/* -zt
    /usr/bin/bsdtar -f - -t --exclude="*/*"
    echo "$? -> $@" > /tmp/first.txt

elif [ ! -e /tmp/second.txt ]; then
    # -C /tmp/tmp.y5MlX6Es6K -xz ./tools/common/petalinux/utils/petalinux-install
    /usr/bin/bsdtar -f - -x -C $2 $4
    echo "$? -> $@" > /tmp/second.txt

elif [ ! -e /tmp/third.txt ]; then
    # --exclude=*/* -zt
    /usr/bin/bsdtar -f - -t --exclude="*/*"
    echo "$? -> $@" > /tmp/third.txt

elif [ ! -e /tmp/fourth.txt ]; then
    # -C /tmp/tmp.bIKyw4tET6 -xz ./tools/common/petalinux/utils/petalinux-env-check ./etc/license/Petalinux_EULA.txt ./etc/license/WebTalk_notice.txt ./etc/license/Third_Party_Software_End_User_License_Agreement.txt
    /usr/bin/bsdtar -f - -x -C $2 $4 $5 $6 $7
    echo "$? -> $@" > /tmp/fourth.txt

elif [ ! -e /tmp/fifth.txt ]; then
    # -C /opt/Xilinx/petalinux -xz
    /usr/bin/bsdtar -f - -x -C $2
    echo "$? -> $@" > /tmp/fifth.txt

elif [ ! -e /tmp/sixth.txt ]; then
    # xJ -C /opt/Xilinx/petalinux/components/yocto/source/aarch64 --checkpoint=.2500 --exclude=ext-sdk-prepare.py
    /usr/bin/bsdtar -f - -x -C $3 --exclude=ext-sdk-prepare.py
    echo "$? -> $@" > /tmp/sixth.txt

elif [ ! -e /tmp/seventh.txt ]; then
    # xJ -C /opt/Xilinx/petalinux/components/yocto/source/aarch64/buildtools --checkpoint=.2500
    /usr/bin/bsdtar -f - -x -C $3
    echo "$? -> $@" > /tmp/seventh.txt

elif [ ! -e /tmp/eighth.txt ]; then
    # xJ -C /opt/Xilinx/petalinux/components/yocto/source/arm --checkpoint=.2500 --exclude=ext-sdk-prepare.py
    /usr/bin/bsdtar -f - -x -C $3 --exclude=ext-sdk-prepare.py
    echo "$? -> $@" > /tmp/eighth.txt

elif [ ! -e /tmp/nineth.txt ]; then
    # xJ -C /opt/Xilinx/petalinux/components/yocto/source/arm/buildtools --checkpoint=.2500
    /usr/bin/bsdtar -f - -x -C $3
    echo "$? -> $@" > /tmp/nineth.txt

elif [ ! -e /tmp/tenth.txt ]; then
    # xJ -C /opt/Xilinx/petalinux/components/yocto/source/microblaze_full --checkpoint=.2500 --exclude=ext-sdk-prepare.py
    /usr/bin/bsdtar -f - -x -C $3 --exclude=ext-sdk-prepare.py
    echo "$? -> $@" > /tmp/tenth.txt

elif [ ! -e /tmp/twelve.txt ]; then
    # xJ -C /opt/Xilinx/petalinux/components/yocto/source/microblaze_full/buildtools --checkpoint=.2500
    /usr/bin/bsdtar -f - -x -C $3 --exclude=ext-sdk-prepare.py
    echo "$? -> $@" > /tmp/twelve.txt

elif [ ! -e /tmp/thirteen.txt ]; then
    # xJ -C /opt/Xilinx/petalinux/components/yocto/source/microblaze_lite --checkpoint=.2500 --exclude=ext-sdk-prepare.py
    /usr/bin/bsdtar -f - -x -C $3
    echo "$? -> $@" > /tmp/thirteen.txt

elif [ ! -e /tmp/fourteen.txt ]; then
    # xJ -C /opt/Xilinx/petalinux/components/yocto/source/microblaze_lite/buildtools --checkpoint=.2500
    /usr/bin/bsdtar -f - -x -C $3
    echo "$? -> $@" > /tmp/fourteen.txt

elif [ ! -e /tmp/fifteen.txt ]; then
    # -xf /opt/Xilinx/petalinux/./tools/yocto-esdk/aarch64.tar -C /opt/Xilinx/petalinux/./components/yocto/source/aarch64/../
    /usr/bin/bsdtar -f $2 -x -C $4
    echo "$? -> $@" > /tmp/fifteen.txt

elif [ ! -e /tmp/sixteen.txt ]; then
    # -xf /opt/Xilinx/petalinux/./tools/yocto-esdk/arm.tar -C /opt/Xilinx/petalinux/./components/yocto/source/arm/../
    /usr/bin/bsdtar -f $2 -x -C $4
    echo "$? -> $@" > /tmp/sixteen.txt

elif [ ! -e /tmp/seventeen.txt ]; then
    echo "Not implemented --> $@" > /tmp/seventeen.txt

else
    echo "additional $@" --> /tmp/additional.txt
fi
```

**Comment by z4yx** [comment]
Here is a successful log while installing petalinux 2018.3 in Docker for your reference
Docker version 1.13.1, build 092cba3

```
Step 10/16 : RUN chmod a+x /${PETA_RUN_FILE} &&   mkdir -p /opt/Xilinx &&   chmod 777 /tmp /opt/Xilinx &&   cd /tmp &&   sudo -u vivado /accept-eula.sh /${PETA_RUN_FILE} /opt/Xilinx/petalinux &&   rm -f /${PETA_RUN_FILE} /accept-eula.sh                 
 ---> Running in 5ae046e1eb5b
spawn /petalinux-v2018.3-final-installer.run /opt/Xilinx/petalinux
INFO: Checking installation environment requirements...
INFO: Checking free disk space
INFO: Checking installed tools
dpkg: warning: failed to open configuration file '/root/.dpkg.cfg' for reading: Permission denied
dpkg: warning: failed to open configuration file '/root/.dpkg.cfg' for reading: Permission denied
dpkg: warning: failed to open configuration file '/root/.dpkg.cfg' for reading: Permission denied
INFO: Checking installed development libraries
INFO: Checking network and other services
WARNING: No tftp server found - please refer to "PetaLinux SDK Installation Guide" for its impact and solution
INFO: Checking installer checksum...
INFO: Extracting PetaLinux installer...

LICENSE AGREEMENTS

PetaLinux SDK contains software from a number of sources.  Please review
the following licenses and indicate your acceptance of each to continue.

You do not have to accept the licenses, however if you do not then you may
not use PetaLinux SDK.

Use PgUp/PgDn to navigate the license viewer, and press 'q' to close

Press Enter to display the license agreements
WARNING: terminal is not fully functional
Do you accept Xilinx End User License Agreement? [y/N] > y
WARNING: terminal is not fully functional
Do you accept Webtalk Terms and Conditions? [y/N] > y)
WARNING: terminal is not fully functional
Do you accept Third Party End User License Agreement? [y/N] > yment.txt  (press RETURN)
INFO: Installing PetaLinux...
INFO: Checking PetaLinux installer integrity...
INFO: Installing PetaLinux SDK to "/opt/Xilinx/petalinux/."
INFO: Installing aarch64 Yocto SDK to "/opt/Xilinx/petalinux/./components/yocto/source/aarch64"...
INFO: Installing arm Yocto SDK to "/opt/Xilinx/petalinux/./components/yocto/source/arm"...
INFO: Installing microblaze_full Yocto SDK to "/opt/Xilinx/petalinux/./components/yocto/source/microblaze_full"...
INFO: Installing microblaze_lite Yocto SDK to "/opt/Xilinx/petalinux/./components/yocto/source/microblaze_lite"...
INFO: PetaLinux SDK has been installed to /opt/Xilinx/petalinux/.
 ---> 01ed694bc430
Removing intermediate container 5ae046e1eb5b
Step 11/16 : USER vivado
 ---> Running in 0688be96ebf8
 ---> 44d3a9f0d8b6
Removing intermediate container 0688be96ebf8
Step 12/16 : ENV HOME /home/vivado
 ---> Running in 7a766e1ecd88
 ---> b3f97311aba3
Removing intermediate container 7a766e1ecd88
Step 13/16 : ENV LANG en_US.UTF-8
 ---> Running in 22604407a8d5
 ---> e5e4a2b8caa3
Removing intermediate container 22604407a8d5
Step 14/16 : RUN mkdir /home/vivado/project
 ---> Running in 443a5647aa7a
 ---> 302f2993f005
Removing intermediate container 443a5647aa7a
Step 15/16 : WORKDIR /home/vivado/project
 ---> 5b699b8980c6
Removing intermediate container 3963732b28bc
Step 16/16 : RUN echo "source /opt/Xilinx/petalinux/settings.sh" >> /home/vivado/.bashrc
 ---> Running in 916780dc0769
 ---> 96041ad86a88
Removing intermediate container 916780dc0769
Successfully built 96041ad86a88
```

**Comment by Mon-ius** [comment]
How to alias it as tar? Copy it to .bashrc ? or save it as a script in /opt/tar.sh and alias tar=/opt/tar.sh ? Confused...never did such alias.

**Comment by Mon-ius** [comment]
```
PetaLinux SDK contains software from a number of sources.  Please review
the following licenses and indicate your acceptance of each to continue.

You do not have to accept the licenses, however if you do not then you may
not use PetaLinux SDK.

Use PgUp/PgDn to navigate the license viewer, and press 'q' to close

Press Enter to display the license agreements
./petalinux-v2018.3-final-installer.run: line 124: less: command not found
Do you accept Xilinx End User License Agreement? [y/N] > y
./petalinux-v2018.3-final-installer.run: line 124: less: command not found
Do you accept Webtalk Terms and Conditions? [y/N] > y
./petalinux-v2018.3-final-installer.run: line 124: less: command not found
Do you accept Third Party End User License Agreement? [y/N] > y
INFO: Installing PetaLinux...
tar: Error opening archive: Failed to open '/dev/st0'
INFO: Checking PetaLinux installer integrity...
INFO: Installing PetaLinux SDK to "/home/monius/peta/"
*********************************************
ERROR: Failed to install PetaLinux SDK into "/home/monius/peta/"
*********************************************

Please refer to the PetaLinux Tools Installation Guide.

Check the troubleshooting guide at the end of that manual, and if you are
unable to resolve the issue please contact customer support with file:
   /home/monius/petalinux_installation_log

monius@3c95488ab50b:~$ cat /home/monius/petalinux_installation_log

INFO: Checking installation environment requirements...
INFO: Checking installer checksum...
INFO: Extracting PetaLinux installer...
INFO: Installing PetaLinux...
INFO: Checking PetaLinux installer integrity...
INFO: Installing PetaLinux SDK to "/home/monius/peta/"
tar: Option --checkpoint=.5000 is not supported
Usage:
  List:    tar -tf <archive-filename>
  Extract: tar -xf <archive-filename>
  Create:  tar -cf <archive-filename> [filenames...]
  Help:    tar --help
*********************************************
ERROR: Failed to install PetaLinux SDK into "/home/monius/peta/"
*********************************************
Please refer to the PetaLinux Tools Installation Guide.

Check the troubleshooting guide at the end of that manual, and if you are
unable to resolve the issue please contact customer support with file:
   /home/monius/petalinux_installation_log
```

I save your code in ~/bin/tar and give x to it. And alias tar='~/bin/tar' , still got error. QAQ

**Comment by Mon-ius** [comment]
Here is my docker config in Mac OSX
```

Client: Docker Engine - Community
 Version:           18.09.2
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        6247962
 Built:             Sun Feb 10 04:12:39 2019
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.2
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.6
  Git commit:       6247962
  Built:            Sun Feb 10 04:13:06 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```

**Comment by Mon-ius** [comment]
I tested everything well with ubuntu and debian in VM, but failed in Docker

**Comment by njskalski** [comment]
I just wasted way too much time trying to build in Docker, the script is just broken. I just went to install it outside and use tar.gz , wonder how that will come back at me.

Is it possible to run dockerfile in VM in automated way?

**Comment by Spartak0s** [comment]
I had the same issue. Privileges worked fine, but got me to another error about yocto.  Finally solved it.
For me yocto got installed after installing python2.7 , which was not included in my system.
`sudo apt-get install python` should work. All other solutions didn't work for me.

I hope it helps!

**Comment by deepakravibabu** [comment]
> I had the same issue. Privileges worked fine, but got me to another error about yocto. Finally solved it.
> For me yocto got installed after installing python2.7 , which was not included in my system.
> `sudo apt-get install python` should work. All other solutions didn't work for me.
> 
> I hope it helps!

**Comment by thechosenone98** [comment]
Installing Python2 resolved the issue but you have to create a symbolic link like so
`sudo ln -s /usr/bin/python2 /usr/bin/python` otherwise the tool won’t be able to launch it (there is most likely an environment variable that you could change to the /usr/bin/python2 path in order for the tool to launch it without a symbolic link but this works…).

Note: the reason for the symbolic link is most likely due to my version of ubuntu (22.04) no longer installing python2 like this
`sudo apt install python`
but like this
`sudo apt install python2`
