### ISSUE TITLE
No tftp server found

### ISSUE THREAD

**Issue by nullbyte91** [z4yx/petalinux-docker#5]
Hi,

First of all, thank you so much for this work. I'm getting the below warning,
WARNING: No tftp server found - please refer to "PetaLinux SDK Installation Guide" for its impact and solution

This warning message indicates that we do not have a TFTP service
running on the workstation. Without a TFTP service, we cannot
download Linux system images to the target system using the U-Boot
network/TFTP capabilities. This warning can be ignored for other boot
modes. 

I tried to set up tftp inside docker. But no luck. Can you please provide me some details about how we can this issue?

**Comment by z4yx** [comment]
You may install tftpd-hpa server on your host machine. Then create `/tftpboot` folder inside Docker, and expose that folder to host with `-v /var/lib/tftp:/tftpboot` option. (Replace `/var/lib/tftp` with the actual path of your tftpd service directory)

**Comment by Grekery** [comment]
Step 10/18 :
-bash: /accept-eula.sh: /usr/bin/expect^M: bad interpreter: No such file or directory

**Comment by z4yx** [comment]
Hi @Grekery, it seems that you had edited `accept-eula.sh` on Windows, or cloned this repo on Windows. Changing the line-ending from `\r\n` to `\n` should solve the problem.

**Comment by Grekery** [comment]
#!/usr/bin/expect
set timeout -1
set install_dir [lindex $argv 1]
set installer [lindex $argv 0]

spawn $installer $install_dir
expect "Press Enter to display the license agreements"
send "\r"
set timeout 2

expect {
    "* >*" {send "y\r"}
    timeout { send "q"; sleep 1; exp_continue}
}
expect {
    "* >*" {send "y\r"}
    timeout { send "q"; sleep 1; exp_continue}
}
expect {
    "* >*" {send "y\r"}
    timeout { send "q"; sleep 1; exp_continue}
}

set timeout -1
expect "INFO: Checking PetaLinux installer integrity..."
expect "INFO: PetaLinux SDK has been installed"
#interact



where is \r\n

**Comment by Grekery** [comment]
I know ,thanks

**Comment by z4yx** [comment]
The line-ending symbol is usually invisible. Most code editors can do the conversion. If you only have a command-line environment, please refer to this question: https://superuser.com/questions/156516/is-there-a-bash-command-to-convert-r-n-to-n
