### ISSUE TITLE
Missing package for petalinux 2019.2?

### ISSUE THREAD

**Issue by lukipedio** [z4yx/petalinux-docker#9]
I have tried to use your Dockerfile to generate a Petalinux 2019.2 (using ubuntu:18.04 as base).

It seems there is a couple of packages missing:
python
libncurses5

**Comment by z4yx** [comment]
`libncurses5` should be automatically installed by installing `libncurses5-dev` (already done in Dockerfile). 
I will add `python` to the installation list.

**Comment by lukipedio** [comment]
You are right! I didn't notice libncurses5-dev inclusion.
